### ISSUE TITLE
Stuck transactions on Mm pulsechain 

### ISSUE THREAD

**Issue by Jwhitfi** [poseidonPLS/metamask-pulsechain#1]
I hope you can help me, I had a transaction stuck in metamask and I kept repeating the transaction trying again, I ultimately erased my wallet and recovered it. Once again I try to submit a transaction and everything is stuck.  I watch the YouTube explanation how to fix with the nonce and increase gas, but still no luck. Anyway you can give me some advice?
My address is 0x78173cAdc97432e09d6D00d7894b4074B83762C3 if it helps by looking at block scout or pulse scam.  I would appreciate any help you can give, my hands are tied.   Jonathan

**Comment by Clition-arf** [comment]
> I hope you can help me, 

Hi Jonathan, has your issue been resolved?

**Comment by Gavehenry12** [comment]
> I hope you can help me, I had a transaction stuck in metamask and I kept repeating the transaction trying again, I ultimately erased my wallet and recovered it. Once again I try to submit a transaction and everything is stuck. I watch the YouTube explanation how to fix with the nonce and increase gas, but still no luck. Anyway you can give me some advice?
> My address is 0x78173cAdc97432e09d6D00d7894b4074B83762C3 if it helps by looking at block scout or pulse scam. I would appreciate any help you can give, my hands are tied. Jonathan

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by poseidonPLS** [comment]
Issued closed

**Comment by poseidonPLS** [comment]
Issue closed
